### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "sammidev",
  "password": "Sammidev123"
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "sammidev123",
  "password": "Password12312345"
}

### Update
PUT http://localhost:3000/api/users
Authorization: 7a1a3cb0-5dd5-4023-b967-04b544a628fd
Content-Type: application/json

{
  "username": "sammidev123",
  "password": "Password12312345"
}

### Logout
POST http://localhost:3000/api/auth/logout
Authorization: 7f44c647-0f5b-40b6-af05-87ee28cb5a94
Accept: application/json

### POST video
POST http://localhost:3000/api/videos
Authorization: 5d8254d0-fbb8-4526-b73d-e61964ad9103
Accept: application/json
Content-Type: application/json

{
  "title": "video 1 dhuar dhuar hudar hudahdushd sahudhas",
  "youtube_link": "https://www.youtube.com/watch?v=OBeHTS-dP_s&pp=ygUQc2FtbWkgYWxkaGkgeWFudA%3D%3D"
}

### GET video
GET http://localhost:3000/api/videos/64bbb2368d79b91f6e22434c
Accept: application/json
Content-Type: application/json


### GET all video
GET http://localhost:3000/api/videos
Accept: application/json
Content-Type: application/json

{
    "youtube_link": "https://www.youtube.com/watch?v=wuLKvcn-c7A"
}

### create product
POST http://localhost:3000/api/products
Authorization: 72373da5-0823-4fb4-a13c-e7a702489aff
Accept: application/json
Content-Type: application/json

{
  "name": "product 2",
  "price": 1000,
  "video_id": "64bbe20ba549f99ae1e2f7c7",
  "product_link": "https://shopee.co.id/%F0%9D%97%B6%F0%9D%97%95%F0%9D%97%BC%F0%9D%98%85%C2%AE-Macbook-Pro-M1-Pro-Chip-2021-14-inch-RAM-16GB-SSD-512GB-1TB--i.148846460.3839729412"
}

### get product by id
GET http://localhost:3000/api/products/64bb3ce37e120653c4307d8f
Accept: application/json

### get all product
GET http://localhost:3000/api/products
Accept: application/json

### get all product by video id
GET http://localhost:3000/api/products/video/64bb245dcebfdc91b4176da5
Accept: application/json

### create comment
POST http://localhost:3000/api/comments
Authorization: 72373da5-0823-4fb4-a13c-e7a702489aff
Accept: application/json
Content-Type: application/json

{
  "video_id": "64bbe1d2a549f99ae1e2f7bb",
  "text": "llal"
}

### get list comment by video id
GET http://localhost:3000/api/comments/video/64bbc86303dd5bc7f7d9ad2f
Accept: application/json

### DELETE VIDEO
DELETE http://localhost:3000/api/videos/64bbac13bf3f459efa4a1965
Authorization: 4dcc009f-a877-455c-a589-1e55abeb7f33
Accept: application/json
